server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/puhaiyang/spring-boot-cloud.git
          search-paths: config-repo
          timeout: 20
    kubernetes:
      discovery:
        enabled: true