ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

feign:
  hystrix:
    enabled: true

spring:
  kubernetes:
    enabled: true
    discovery:
      enabled: true
      all-namespaces: true
    config:
      namespace: default

