ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

feign:
  hystrix:
    enabled: true

spring:
  cloud:
    kubernetes:
      discovery:
        enabled: true
      client:
        namespace: default
