spring:
  application:
    name: zipkin
  rabbitmq:
    host: rabbitmq
    port: 30672
    username: user
    password: bitnami

server:
  port: 9411

security:
  user:
    name: admin
    password: ${ZIPKIN_SERVER_PASSWORD:admin}
