#-------------registry-----------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - image: ccr.ccs.tencentyun.com/spring-boot-cloud/registry:latest
          imagePullPolicy: Always
          name: registry
          ports:
            - containerPort: 8761
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: registry-service
spec:
  ports:
    - name: http
      port: 8761
      protocol: TCP
      targetPort: 8761
  selector:
    app: registry
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: registry-nginx
spec:
  rules:
    - host: registry.springcloud.com
      http:
        paths:
          - backend:
              serviceName: registry-service
              servicePort: 8761
